table fact_sales
	lineageTag: 4ee3fa87-7e98-42ca-b7de-1d36e80f2679
	sourceLineageTag: [dbo].[fact_sales]

	measure 'Sales Amount' = ```
			
			    SUMX (
			        'fact_sales',
			        'fact_sales'[Quantity] * 'fact_sales'[UnitPrice]
			    )
			    
			```
		lineageTag: 7b2a21cc-dc92-4693-8e9c-074d58903cac

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Cost' = ```
			
			    SUMX (
			        'fact_sales',
			        'fact_sales'[Quantity] * 'fact_sales'[UnitCost]
			    )
			
			```
		lineageTag: d0d629f5-1ed9-4007-8d01-c3247134ca83

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column OrderKey
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 41a8fe59-7abd-4ee3-bb33-10030e065cb9
		sourceLineageTag: OrderKey
		summarizeBy: none
		sourceColumn: OrderKey

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

	column LineNumber
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 508643b1-baf7-4db1-ac29-8b43205a7f2d
		sourceLineageTag: LineNumber
		summarizeBy: none
		sourceColumn: LineNumber

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

	column OrderDate
		dataType: dateTime
		formatString: Short Date
		sourceProviderType: date
		lineageTag: 9f5430dd-0890-4498-aaed-95f765d673bf
		sourceLineageTag: OrderDate
		summarizeBy: none
		sourceColumn: OrderDate

		changedProperty = DataType

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column DeliveryDate
		dataType: dateTime
		formatString: Short Date
		sourceProviderType: date
		lineageTag: dd374308-6936-41e8-b931-e71eca3df533
		sourceLineageTag: DeliveryDate
		summarizeBy: none
		sourceColumn: DeliveryDate

		changedProperty = IsHidden

		changedProperty = DataType

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column CustomerKey
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: int
		lineageTag: 91aac3fd-7a72-4034-9859-e846a66fbb0c
		sourceLineageTag: CustomerKey
		summarizeBy: none
		sourceColumn: CustomerKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column StoreKey
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: int
		lineageTag: 8831ed3f-7ba5-4334-b489-f31b09c4c0e4
		sourceLineageTag: StoreKey
		summarizeBy: none
		sourceColumn: StoreKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ProductKey
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: int
		lineageTag: 455c7b1c-9dba-4c56-96bd-72dc9a56d186
		sourceLineageTag: ProductKey
		summarizeBy: none
		sourceColumn: ProductKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Quantity
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: ecef42f9-8768-49c0-84bb-da16e4b202cc
		sourceLineageTag: Quantity
		summarizeBy: none
		sourceColumn: Quantity

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

	column UnitPrice
		dataType: double
		sourceProviderType: float
		lineageTag: 21c82127-e059-4250-b3ec-dd13922f62f4
		sourceLineageTag: UnitPrice
		summarizeBy: none
		sourceColumn: UnitPrice

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column NetPrice
		dataType: double
		sourceProviderType: float
		lineageTag: ce04f8f1-cc74-4741-a3f6-84d0cb4eb79a
		sourceLineageTag: NetPrice
		summarizeBy: none
		sourceColumn: NetPrice

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column UnitCost
		dataType: double
		sourceProviderType: float
		lineageTag: eceaf85c-ec9c-4a89-860d-13d8ff4a18f8
		sourceLineageTag: UnitCost
		summarizeBy: none
		sourceColumn: UnitCost

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CurrencyCode
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: a7bce141-7f50-409d-8568-71b86e64eec1
		sourceLineageTag: CurrencyCode
		summarizeBy: none
		sourceColumn: CurrencyCode

		annotation SummarizationSetBy = Automatic

	column ExchangeRate
		dataType: double
		sourceProviderType: float
		lineageTag: 13d2fafd-60f2-4d48-a3e3-da21a502b731
		sourceLineageTag: ExchangeRate
		summarizeBy: none
		sourceColumn: ExchangeRate

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition fact_sales = entity
		mode: directLake
		source
			entityName: fact_sales
			schemaName: dbo
			expressionSource: DatabaseQuery

	annotation PBI_ResultType = Table

